fix: update tests

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -76,19 +76,33 @@ abort(){
     printf "%s\n" "$msg"
     exit 1
 }
-test_executable(){
-    local t="$1"
-    [[ ! -x "$t" ]] && abort "Test '${tests[$i]}' is not executable"
+result(){
+    local res="$1"
+    case "$res" in
+        0)
+            printf "Result: OK\n"
+            printf "\n"
+            return 0
+            ;;
+        1)
+            printf "Result: FAIL\n"
+            exit 1
+            ;;
+    esac
 }
-#readarray -t tests < <(find $PWD/tests -type f)
-#for ((i=0; i <${#tests[@]}; ++i)); do
-#    test_executable "${tests[$i]}"
-#    inc=$((i+1))
-#    name=$(awk -F\" '/TEST_NAME/ {print $2}' "${tests[$i]}")
-#    printf "Test %s/%s: %s\n" "$inc" "${#tests[@]}" "$name"
-#        ${tests[$i]}
-#        result "$?"
-#done
+test_executable(){
+    local f="$1"
+    [[ ! -x "$f" ]] && abort "Test '$f' is not executable"
+}
+readarray -t tests < <(find $PWD/tests -type f)
+for ((i=0; i <${#tests[@]}; ++i)); do
+    test_executable "${tests[$i]}"
+    inc=$((i+1))
+    name=$(awk -F\" '/TEST_NAME/ {print $2}' "${tests[$i]}")
+    printf "Test %s/%s: %s\n" "$inc" "${#tests[@]}" "$name"
+    ${tests[$i]}
+    result "$?"
+done
 
 #echo "This commit change is of type:"
 #select opt in "${opts[@]}"; do
